# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 11:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('autor', models.CharField(default='', max_length=200)),
                ('especie', models.CharField(default='', max_length=200)),
                ('bioma', models.CharField(default='', max_length=200)),
                ('descricao', models.TextField(default='')),
                ('votes', models.IntegerField(default=0)),
                ('local', models.TextField(default='')),
                ('published_date', models.DateTimeField(default=datetime.datetime(2017, 10, 22, 11, 7, 52, 897352, tzinfo=utc))),
                ('imagem', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
            ],
        ),
    ]
